// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package pgstore

import (
	"context"
)

// iteratorForInviteParticipiantsToTrip implements pgx.CopyFromSource.
type iteratorForInviteParticipiantsToTrip struct {
	rows                 []InviteParticipiantsToTripParams
	skippedFirstNextCall bool
}

func (r *iteratorForInviteParticipiantsToTrip) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInviteParticipiantsToTrip) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TripID,
		r.rows[0].Email,
	}, nil
}

func (r iteratorForInviteParticipiantsToTrip) Err() error {
	return nil
}

func (q *Queries) InviteParticipiantsToTrip(ctx context.Context, arg []InviteParticipiantsToTripParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"participants"}, []string{"trip_id", "email"}, &iteratorForInviteParticipiantsToTrip{rows: arg})
}
